on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      debug_mode:
        type: boolean
      port_number:
        type: number
    secrets:
      DOCKER_TOKEN:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - run: |
          echo "Deploying to ${{ inputs.environment }}"
          echo "debug mode is ${{inputs.debug_mode}}"
          echo "port is ${{inputs.port_number}}"
      
      #- run: docker login -u user -p ${{ secrets.DOCKER_TOKEN }}
