on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      debug_mode:
        type: boolean
      port_number:
        type: number
    secrets:
      DOCKER_TOKEN:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: docker login -u user -p ${{ secrets.DOCKER_TOKEN }}
